name: End of Life Dependency Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  eol-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install pip-audit
        run: pip install pip-audit

      - name: Run EOL check
        run: pip-audit -r requirements.txt
